<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \SM\Payment\Block\Info\RetailMultiple
 */
?>
<b><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></b>
<br>
<br>
<?php if (is_array($block->getMultiplePaymentData()) && count($block->getMultiplePaymentData()) > 0): ?>
    <?php foreach ($block->getMultiplePaymentData() as $payment): ?>
        <div style="margin-left: 15px">
            <p style="font-weight: 700; text-transform: uppercase"><?php echo $payment['title']; ?>
            <?php if (isset($payment['data']['ref']) && !!$payment['data']['ref']): ?>
                <?php echo ": Ref#" . $payment['data']['ref'] ?>
            <?php endif; ?></p>

            <?php if ($payment['type'] === 'payment_express' && !empty($payment['data']['Result'])): ?>
                <table class="data-table admin__table-secondary">
                    <tbody>
                    <?php if (!empty($payment['data']['Result']['CN'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Masked Card Number')) ?>:</th>
                            <td><?= $payment['data']['Result']['CN'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['Result']['CH'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Card Holder Name')) ?>:</th>
                            <td><?= $payment['data']['Result']['CH'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['Result']['CT'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Card Type')) ?>:</th>
                            <td><?= $payment['data']['Result']['CT'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['Result']['AC'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Authorisation Code')) ?>:</th>
                            <td><?= $payment['data']['Result']['AC'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['Result']['TR'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Transaction Reference')) ?>:</th>
                            <td><?= $payment['data']['Result']['TR'] ?></td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            <?php endif; ?>

            <?php // authorize.net payment details?>
            <?php if ($payment['type'] === 'authorize_net' && !empty($payment['data'])): ?>
                <table class="data-table admin__table-secondary">
                    <tbody>
                    <?php if (!empty($payment['data']['accountType'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Credit Card Type')) ?>:</th>
                            <td><?= $payment['data']['accountType'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['accountNumber'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Credit Card Number')) ?>:</th>
                            <td><?= $payment['data']['accountNumber'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['transId'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Transaction ID')) ?>:</th>
                            <td><?= $payment['data']['transId'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['avsResultCode'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('AVS Response')) ?>:</th>
                            <td><?= $payment['data']['avsResultCode'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['cvvResultCode'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('CCV Response')) ?>:</th>
                            <td><?= $payment['data']['cvvResultCode'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['cavvResultCode'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('CAVV Response')) ?>:</th>
                            <td><?= $payment['data']['cavvResultCode'] ?></td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            <?php endif;?>

            <?php // eway payment details?>
            <?php if ($payment['type'] === 'eway' && !empty($payment['data'])): ?>
                <table class="data-table admin__table-secondary">
                    <tbody>
                    <?php if (!empty($payment['data']['CardNumber'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Card Number')) ?>:</th>
                            <td><?= $payment['data']['CardNumber'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['TransactionID'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Transaction ID')) ?>:</th>
                            <td><?= $payment['data']['TransactionID'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($payment['data']['TransactionType'])): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Transaction Type')) ?>:</th>
                            <td><?= $payment['data']['TransactionType'] ?></td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            <?php endif;?>

            <p><em><?php echo $payment['created_at'] ?></em></p>
            <p><?php echo $block->formatPrice($payment['amount']) ?></p>
        </div>
    <?php endforeach; ?>
<?php else: ?>
<div style="margin-left: 15px">
    <p style="font-weight: 700; text-transform: uppercase"><?php echo $block->getMethodTitle(); ?></p>
</div>
<?php endif; ?>
